apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: grpc-game-server-autoscaler
spec:
  fleetName: grpc-game-server
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 0
      maxReplicas: 10
